# Generated by Django 6.0.7 on 2026-08-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='ambulance_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_number', models.IntegerField()),
                ('vehicle_model', models.CharField(max_length=200)),
                ('registration_number', models.IntegerField()),
                ('manufacturing_year', models.DateField(verbose_name=0)),
                ('capacity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason_for_visit', models.CharField(max_length=300)),
                ('booked_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='beds_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('bed_type', models.CharField(max_length=200)),
                ('floor_number', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('bed_status', models.CharField(max_length=200)),
                ('patient', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_date', models.DateField()),
                ('discharge_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=100, null=True)),
                ('department_head', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('floor_number', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('opening_time', models.TimeField(null=True)),
                ('closing_time', models.TimeField(null=True)),
                ('total_doctors', models.IntegerField()),
                ('total_nurses', models.IntegerField()),
                ('status', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_perinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(default=None, max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='floor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=200)),
                ('floor_num', models.IntegerField()),
                ('floor_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('dosage_form', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('quantity_in_stock', models.CharField(max_length=200)),
                ('unit_price', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('prescription_required', models.TextField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient_contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient_emergency_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_con_name', models.CharField(max_length=100)),
                ('emergency_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('martial_status', models.CharField(max_length=35)),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='patient_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_provider', models.CharField(max_length=200)),
                ('insurance_policy_number', models.CharField(max_length=200)),
                ('insuarance_expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='patient_Medical_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(blank=True, max_length=150)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('current_medication', models.CharField(blank=True, max_length=250, null=True)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recep_person_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=200)),
                ('floor_number', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.CharField(max_length=200)),
                ('occupied_beds', models.IntegerField()),
                ('available_beds', models.CharField(blank=True, max_length=200, null=True)),
                ('room_status', models.CharField(max_length=200)),
                ('daily_charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('per_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
            ],
        ),
        migrations.CreateModel(
            name='doctors_hos_infp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('office_num', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('res_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
            ],
        ),
        migrations.CreateModel(
            name='doctors_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsProfessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_lincense_num', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=150)),
                ('years_of_experience', models.IntegerField()),
                ('consultation_fee', models.CharField(blank=True, max_length=200, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.department')),
                ('pro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
            ],
        ),
        migrations.CreateModel(
            name='driver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_hospital', models.CharField(max_length=200)),
                ('assigned_staff', models.CharField(max_length=200)),
                ('availability_status', models.CharField(max_length=100)),
                ('ambu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.ambulance_info')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='maintenance_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField()),
                ('maintenance_notes', models.TextField()),
                ('fuel_status', models.CharField(max_length=150)),
                ('amser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.ambulance_info')),
            ],
        ),
        migrations.CreateModel(
            name='nurse_employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('nursing_license_number', models.CharField(max_length=200)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('nu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.nurse_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='nurse_contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('nurse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.nurse_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='doctors_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_appointments', models.IntegerField()),
                ('total_patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient_info')),
            ],
        ),
        migrations.CreateModel(
            name='recep_employ_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.FloatField()),
                ('status', models.CharField(max_length=150)),
                ('desk_number', models.IntegerField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('sec_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.recep_person_info')),
            ],
        ),
        migrations.CreateModel(
            name='recep_contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_number', models.CharField(max_length=200)),
                ('recep_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.recep_person_info')),
            ],
        ),
        migrations.CreateModel(
            name='patient_hopital_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeration_date', models.DateField()),
                ('patient_type', models.CharField(max_length=50)),
                ('addmission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('patient_status', models.CharField(max_length=50)),
                ('assisgned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
                ('bed_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.beds_info')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.department')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.room_info')),
            ],
        ),
        migrations.CreateModel(
            name='nurse_work_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor_perinfo')),
                ('se_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.nurse_personal_info')),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.room_info')),
            ],
        ),
    ]
