# Generated by Django 6.0.7 on 2026-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='total_doctors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='total_nurses',
            field=models.IntegerField(null=True),
        ),
    ]
