# Generated by Django 6.0.7 on 2026-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0002_alter_department_total_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofessioninfo',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
