# Generated by Django 6.0.7 on 2026-09-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0005_beds_info_user_department_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beds_info',
            name='department',
        ),
    ]
