# Generated by Django 6.0.7 on 2026-09-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0006_remove_beds_info_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='floor_number',
        ),
    ]
