# Generated by Django 6.0.7 on 2026-09-02 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0007_remove_department_floor_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='users_login',
        ),
        migrations.AddField(
            model_name='patient_contact_info',
            name='pat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient_info'),
        ),
        migrations.AddField(
            model_name='patient_emergency_con',
            name='pat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient_info'),
        ),
        migrations.AddField(
            model_name='patient_medical_info',
            name='pat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient_info'),
        ),
    ]
