# Generated by Django 6.0.7 on 2026-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0008_rename_login_users_login_patient_contact_info_pat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_info',
            name='ambulance_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance_info',
            name='registration_number',
            field=models.CharField(max_length=200),
        ),
    ]
